functionland/fx-files

Functionland.FxFiles/App/Functionland.FxFiles.App.csproj, Functionland.FxFiles/Web/Extensions/IServiceCollectionExtensions.cs, Functionland.FxFiles/Web/Functionland.FxFiles.Web.csproj, Functionland.FxFiles/Web/Pages/Settings.razor.cs, Functionland.FxFiles/Web/Pages/ThemeSettings.razor.cs, Functionland.FxFiles/Web/Shared/MainLayout.razor.cs
=> Remove "Functionland.FxFiles.App.Components" from implicit using. ab#7

Functionland.FxFiles/Shared/Resources/AppStrings.Designer.cs, Functionland.FxFiles/Shared/Resources/AppStrings.resx, Functionland.FxFiles/Web/Pages/HomePage.razor, Functionland.FxFiles/Web/Pages/HomePage.razor.cs, Functionland.FxFiles/Web/Pages/Settings.razor
=> Move TestExplorer btn to Setting page. ab#270

Functionland.FxFiles/Shared/TestInfra/Implementations/FileServicePlatformTest.cs
=> Handle final exception in FileServicePlatformTest. ab#270

Functionland.FxFiles/Web/Components/DesignSystem/FxBottomSheet.razor.cs
=> Modify FxBottomSheet ab#299

Functionland.FxFiles/Web/Components/Modal/ToastModal/ToastModal.razor.scss
Co-Authored-By: Hootan HT <hootanhemmati@outlook.com>
=> Add toast  ab#299

Functionland.FxFiles/Web/Components/DesignSystem/FxButton.razor.scss
=> Add disable mode button ab#75

Functionland.FxFiles/Web/Components/DesignSystem/FxToast.razor.scss, Functionland.FxFiles/Web/Components/Modal/ToastModal/ToastModal.razor.scss
=> Add new size toast modal ab#299

Functionland.FxFiles/Web/Components/FileDetailView.razor.scss, Functionland.FxFiles/Web/Components/FileDetailViewBottomActionItem.razor.scss, Functionland.FxFiles/Web/Pages/HomePage.razor, Functionland.FxFiles/Web/Pages/HomePage.razor.cs
=> Fix scroll bar in file details modal ab#300

src/Client/Shared/Services/Implementations/PinService.cs
=> fix pin service problems ab#359

src/Client/Shared/Services/Implementations/PinService.cs
=> bug fix ab#215

src/Client/App/Platforms/Windows/Package.appxmanifest
=> Set Publisher CN to Function Land ab#264

src/Client/Shared/Components/ArtifactExplorer/ArtifactExplorer.razor, src/Client/Shared/Components/ArtifactExplorer/ArtifactExplorer.razor.cs, src/Client/Shared/Components/FileBrowser/FileBrowser.razor
…plorer. [AB#382](https://dev.azure.com/Functionland/1ecafc59-99e6-4081-9036-1c592c9f5fd4/_workitems/edit/382)
=> Add move functionality to select destination component in artifact ab#365

src/Clean-CSS.bat, src/commands.json
=> Add Clean-CSS.bat ab#410

src/Client/Shared/Components/Modal/ToastModal/ToastModal.razor.cs
…ed. [AB#510](https://dev.azure.com/Functionland/1ecafc59-99e6-4081-9036-1c592c9f5fd4/_workitems/edit/510)
=> Add toast functionality to close automatically in 5 second after showed ab#243

src/Client/Shared/Components/FileBrowser/FileBrowser.razor, src/Client/Shared/Components/FileBrowser/FileBrowser.razor.scss, src/Directory.build.props
Co-Authored-By: Zahra Bayat <Zahra.bayat13799@gmail.com>
=> Fix empty list pinned ab#365

src/Client/App/Platforms/iOS/Extensions/IServiceCollectionExtensions.cs
Resolve conflict. remove additional register. [AB#340](https://dev.azure.com/Functionland/1ecafc59-99e6-4081-9036-1c592c9f5fd4/_workitems/edit/340)
=> Resolve conflict. remove additional register. ab#429

src/Client/Shared/Components/FileBrowser/FileBrowser.razor.cs, src/Client/Shared/Components/FileDetailViewBottomActionItem.razor.cs, src/Client/Shared/Components/FileDetailViewBottomActionItem.razor.scss, src/Client/Shared/Components/Modal/ArtifactDetailModal/ArtifactDetailModal.razor, src/Client/Shared/Components/Modal/ArtifactDetailModal/ArtifactDetailModal.razor.cs, src/Client/Shared/Components/Modal/ArtifactDetailModal/ArtifactOverflowResultType.cs, src/Client/Shared/compilerconfig.json
Co-Authored-By: Mohammad Hosein Rastegarinia <mh.rastegari@outlook.com>
=> Fix unpin issue ab#547

src/Client/Shared/Enums/FsArtifactChangesType.cs, src/Client/Shared/Services/Implementations/FileWatchService.cs, src/Client/Shared/Services/Implementations/PinService/LocalDevicePinService.cs
=> problem with rename in file watch service ab#1021

src/Client/Shared/Services/Implementations/FileWatchService.cs
=> Add on delete  event ab#1021

src/Client/App/Platforms/Android/Implementations/AndroidImageThumbnailPlugin.cs, src/Client/App/Platforms/Android/Implementations/AndroidVideoThumbnailPlugin.cs, src/Client/App/Platforms/Windows/Extensions/IServiceCollectionExtensions.cs, src/Client/App/Platforms/Windows/Implementations/WindowsImageThumbnailPlugin.cs, src/Client/App/Platforms/Windows/Implementations/WindowsVideoThumbnailPlugin.cs, src/Client/Shared/Services/Implementations/Thumbnail/Plugins/ImageThumbnailPlugin.cs, src/Client/Shared/Services/Implementations/Thumbnail/Plugins/PdfThumbnailPlugin.cs, src/Client/Shared/Services/Implementations/Thumbnail/Plugins/VideoThumbnailPlugin.cs
Fix some registration issues, and categorize supported formats for creating thumbnails in Windows and Android.
=> Fix thumbnail plugin bugs. ab#784

src/Client/App/Platforms/Windows/Implementations/WindowsAudioThumbnailPlugin.cs
=> Don't throw exception if stream fills ab#828

docs/class-diagram-overview.md
=> Fix: typos

src/Client/Shared/Components/FileBrowser/FileBrowser.razor, src/Client/Shared/Components/FileBrowser/FileBrowser.razor.cs
Co-Authored-By: Hootan HT <hootanhemmati@outlook.com>
=> fix close keyboard search ab#629

src/Client/Shared/Components/FileBrowser/FileBrowser.razor.cs
Co-Authored-By: Zahra Bayat <Zahra.bayat13799@gmail.com>
=> Handle closing image when oprating on image. ab#888

src/Client/Shared/Components/FileBrowser/FileBrowser.razor.cs
Co-Authored-By: Zahra Bayat <Zahra.bayat13799@gmail.com>
=> Fix remaining selection ab#888

src/Client/App/Platforms/Android/Implementations/LocalAndroidTxtLogger.cs, src/Client/Shared/Components/Modal/FileViewerModal/FileViewer.razor.cs, src/Client/Shared/Components/Modal/FileViewerModal/ZipViewer.razor.cs, src/Client/Shared/Pages/HomePage.razor.cs
Co-Authored-By: negar <negar.ghasemi@hotmail.com>
=> Fix ApplyIntentArtifactIfNeeded bug on Home page. ab#1604 ab#888
